//Tia Hannes - Hanne123 - 5286175
//Thomas Rooney - Roone194 - 5364798

public enum QueryType {
    CREATE_STATEMENT,
    INSERT_STATEMENT,
    LOAD_STATEMENT,
    STORE_STATEMENT,
    PRINT_STATEMENT,
    SELECT_STATEMENT,
    EXIT_STATEMENT
}
